### ISSUE TITLE
Frontmatter query errors

### ISSUE THREAD

**Issue by rickyvetter** [angeloocana/gatsby-plugin-i18n#1]
Hi @angeloocana - first off - thanks so much for making this plugin! It looks like it's pretty new and it's exactly what I'm looking for.

Looking to add this to https://reasonml.github.io/ - ([github project here](https://github.com/reasonml/reasonml.github.io)) and I'm running into issues.

When I run `gatsby develop` it has the following errors: 

```
i18n createPage error:
[ { GraphQLError: Argument "filter" has invalid value {frontmatter: {draft: {ne: true}}}.
  In field "frontmatter": In field "draft": Unknown field.
      at Object.Argument (/path/to/reasonml.github.io/node_modules/graphql/validation/rules/ArgumentsOfCorrectType.js:42:31)
  ...

{ GraphQLError: Cannot query field "tags" on type "frontmatter".
  at Object.Field (/path/to/reasonml.github.io/node_modules/graphql/validation/rules/FieldsOnCorrectType.js:66:31)
  ...
```

At first I thought that it must need some other plugin/transformer that we don't have, but I tried to follow the setup in https://github.com/angeloocana/angeloocana/blob/master/gatsby-config.js as closely as possible and wasn't able to get past that error. Any ideas on what I could do to get the ReasonML setup working with this plugin?

**Comment by rickyvetter** [comment]
Ahh - I see that there is a workaround for this by adding the draft and tag fields to a post. I'll try to make things work with that. https://github.com/gatsbyjs/gatsby/issues/546

**Comment by angeloocana** [comment]
Hi @rickyvetter !

Are you still having problems?

I'm thinking in creating gatsby-plugin-i18n-TAGS and gatsby-plugin-i18n-READNEXT
I need to clean this plugin in order to be able to work with less dependencies.

I wish I could see how did you do it to work.

Thanks!

**Comment by angeloocana** [comment]
@rickyvetter  I removed the draft and tags. Could you try the new version?

I moved the tags to https://github.com/angeloocana/gatsby-plugin-i18n-tags

**Comment by rickyvetter** [comment]
Will try the new version soon this week and report back w/ any issues I have! Thanks for splitting up.

**Comment by angeloocana** [comment]
You are welcome!
Thank you for using and contributing =D
