### ISSUE TITLE
react-i18next, translation keys and translation services

### ISSUE THREAD

**Issue by sedubois** [angeloocana/gatsby-plugin-i18n#10]
Hi, thanks for sharing this plugin. Do you intend to share an example to integrate with react-i18next? Right now the examples are duplicating the code between different languages, but I think they should show how to use translation keys, which avoids code duplication altogether and is compatible with translation services such as locize or other.

Right now the setup has been too complicated for me, so I didn't get a working setup yet.

**Comment by angeloocana** [comment]
Hi @sedubois , 

Thank you for trying out gatsby-plugin-i18n.

It looks like a lot of folks use react-i18next.
I'm looking forward to implementing an example using it,
I can't give you a date right now, but it is on my to-do list.

It would be awesome if other folks send their own projects.
Pull Requests are welcome =D
I'll leave this ISSUE open until we get some example projects.

**Comment by sedubois** [comment]
Thanks that would be really helpful; and to have a whole setup where HMR is functional as well.

**Comment by sedubois** [comment]
NB: a better alternative might be react-intl which is probably more popular than i18next. I only mentioned the latter, because it is the one suggested in this Gatsby blog post: https://www.gatsbyjs.org/blog/2017-10-17-building-i18n-with-gatsby/

The best option of course would be to be able to support both.

**Comment by angeloocana** [comment]
What is HMR?

This plugin can be used with both, react-intl and react-i18next. It can be used with anyone.

I have 3 projects using react-intl:

[gatsby-starter-default-i18n](https://gatsby-starter-default-i18n.netlify.com) [source](https://github.com/angeloocana/gatsby-starter-default-i18n)
[tic-tac-toe.surge.sh](http://tic-tac-toe-ai.surge.sh/) [source](https://github.com/angeloocana/tic-tac-toe-ai)
[angeloocana.com]() [source](https://github.com/angeloocana/angeloocana)

**Comment by sedubois** [comment]
HMR is hot module replacement. I further tried to use react-i18next, but I had to do really hacky things just to get HMR working which should IMHO work out of the box; it looks like a better option to use react-intl like you did in your starter, thanks for providing that! I'm just stuck at the moment because of #6 while trying to integrate it in my Gatsby site.

NB: I think it could be highlighted in the README what the demo showcases, as it's quite valuable info: uses react-intl, uses translation keys, custom layout per language, browser language detection, redirection, etc.

**Comment by sedubois** [comment]
Also, when integrating with my site, I got an error `TypeError: Cannot read property 'site' of undefined`  in the TemplateWrapper, it took me a while to figure out but it came from a conflict between the template and the layout which both have a `pageQuery`. Actually in the Gatsby examples, they never have a pageQuery at the layout level.

Could you maybe move that pageQuery logic into a template, in your own gatsby-starter-default-i18n?

Or doing like I did, avoiding the GraphQL query altogether by directly importing the `data/languages` file from the layout file.

**Comment by angeloocana** [comment]
Sorry if I forget something.

Did you create a duplicated name for the query?
Gatsby gives you an error if it finds duplicated queries names.

You can manually import the languages, I was doing that at the beginning,
but I think Graphql is way more powerful. When I started queries were not allowed in Layouts and now it is =D.

**Comment by angeloocana** [comment]
Would you like to create a PR with that:
```
NB: I think it could be highlighted in the README what the demo showcases, as it's quite valuable info: uses react-intl, uses translation keys, custom layout per language, browser language detection, redirection, etc.
```

I could do that if you are short on time.

**Comment by sedubois** [comment]
See #13

**Comment by sedubois** [comment]
There was no such Gatsby error, only `TypeError: Cannot read property 'site' of undefined`. Some things aren't resolved in the proper order I suppose. It would help if the pages themselves also had GraphQL queries to see how it fits together with the layout query.

**Comment by angeloocana** [comment]
Issue fixed: https://github.com/angeloocana/gatsby-plugin-i18n/issues/6#issuecomment-345404777
