### ISSUE TITLE
How to set index page link to domain/langKey/ instead of domain/index.langKey/

### ISSUE THREAD

**Issue by lewis-geek** [angeloocana/gatsby-plugin-i18n#137]
I have a file named `index.langKey.txs` under the pages folder, the link of this page is `domain/index.langKey/`, how can I set this link to `domain/langKey/` instead of `domain/index.langKey/`?

**Comment by lewis-geek** [comment]
Hi @hugomn ! your site [hugo.im](www.hugo.im) is awesome! do you know how to set this?

**Comment by lewis-geek** [comment]
I fixed the issue by added `${__dirname}/src/pages` to the pagesPaths option,  the root cause is I had added another path to this option.

**Comment by hugomn** [comment]
Hi @lewis-geek! Thanks! Happy that you fixed the issue.
