### ISSUE TITLE
Link to GitHub from NPM

### ISSUE THREAD

**Issue by sedubois** [angeloocana/gatsby-plugin-i18n#15]
This GitHub repo doesn't seem to be linked from the [NPM package page](https://www.npmjs.com/package/gatsby-plugin-i18n).

**Comment by angeloocana** [comment]
Thanks!
Would you like to open a Pull Request?

**Comment by angeloocana** [comment]
The package.json already has a link to the Github page.
I don`t know why NPM is not using it. Do you have any clue?

**Comment by sedubois** [comment]
Don't know either, maybe try same semantics as Gatsby package for homepage and repository fields : 
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/package.json

I suggest you do it as you are the one who can test publishing to NPM.

**Comment by angeloocana** [comment]
Thank you @sedubois  !!!

I think is the 'homepage' prop.
