### ISSUE TITLE
Issue working together with gatsby-source-contentful

### ISSUE THREAD

**Issue by Zangr** [angeloocana/gatsby-plugin-i18n#16]
I recently encountered an issue after including [gatsby-source-contentful](https://www.npmjs.com/package/gatsby-source-contentful) in a project with gatsby-plugin-i18n. gatsby-plugin-i18n doesn't seem to work very well with this contentful plugin.I haven't use gatsby-source-contentful on any pages yet. This plugin is very useful for contentful integration so I really hope gatsby-plugin-i18n can work well with it.

Steps To Reproduce:
- npm install --save gatsby-source-contentful
- configure gatsby-source-contentful as described in its npm page
```
    {
      resolve: `gatsby-source-contentful`,
      options: {
        spaceId: `xxx`,
        accessToken: `xxxxxxx`,
      },
    },
    {
      resolve: 'gatsby-plugin-i18n',
      options: {
        langKeyForNull: 'any',
        langKeyDefault: 'en',
        useLangKeyLayout: false
      }
    },
```
- gatsby develop

```
  TypeError: Cannot read property 'langKey' of undefined

  - onCreateNode.js:49 Object.onCreateNode
    [fe-v2]/[gatsby-plugin-i18n]/onCreateNode.js:49:26
  
  - api-runner-node.js:104 runAPI
    [fe-v2]/[gatsby]/dist/utils/api-runner-node.js:104:36
  
  - api-runner-node.js:178 
    [fe-v2]/[gatsby]/dist/utils/api-runner-node.js:178:33
  
  - map.js:27 
    [fe-v2]/[async]/internal/map.js:27:9
  
  - eachOfLimit.js:64 replenish
    [fe-v2]/[async]/internal/eachOfLimit.js:64:17
  
  - eachOfLimit.js:49 iterateeCallback
    [fe-v2]/[async]/internal/eachOfLimit.js:49:17
  
  - onlyOnce.js:12 
    [fe-v2]/[async]/internal/onlyOnce.js:12:16
  
  - map.js:29 
    [fe-v2]/[async]/internal/map.js:29:13
  
  - util.js:16 tryCatcher
    [fe-v2]/[bluebird]/js/release/util.js:16:23
  
  - nodeify.js:22 Promise.successAdapter [as _fulfillmentHandler0]
    [fe-v2]/[bluebird]/js/release/nodeify.js:22:30
  
  - promise.js:566 Promise._settlePromise
    [fe-v2]/[bluebird]/js/release/promise.js:566:21
  
  - promise.js:614 Promise._settlePromise0
    [fe-v2]/[bluebird]/js/release/promise.js:614:10
  
  - promise.js:693 Promise._settlePromises
    [fe-v2]/[bluebird]/js/release/promise.js:693:18
  
  - async.js:133 Async._drainQueue
    [fe-v2]/[bluebird]/js/release/async.js:133:16
  
  - async.js:143 Async._drainQueues
    [fe-v2]/[bluebird]/js/release/async.js:143:10
  
  - async.js:17 Immediate.Async.drainQueues [as _onImmediate]
    [fe-v2]/[bluebird]/js/release/async.js:17:14
```

**Comment by gucolin** [comment]
@angeloocana any update on this?

**Comment by angeloocana** [comment]
Thank you @Zangr for reporting the bug!

It is fixed!

Upgrade to:
* gatsby-plugin-i18n: 0.4.1
* gatsby-plugin-i18n-readnext: 0.0.4
* gatsby-plugin-i18n-tags: 0.0.3

I'm ignoring contentful pages.

How do you guys are planning to use i18n content in contentful?

**Comment by gucolin** [comment]
Thanks @angeloocana, I'm working with @Zangr on this :) At this point we are exploring as well, so no concrete plan yet. But will keep you posted and probably need your help down the road as we go further into it.

**Comment by Zangr** [comment]
Thank you @angeloocana ! We are trying contentful integration soon and will let you know how it goes with the new version of gatsby-plugin-i18n

**Comment by mccrodp** [comment]
Hey @gucolin, @Zangr , did you get this working? Just came across this issue, I had similar here: https://github.com/angeloocana/gatsby-plugin-i18n/issues/31 Going to try at it again today, but no luck so far.

**Comment by mccrodp** [comment]
I attempted to simplify things and start with the default [using-contentful](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-contentful) example, then try to add this plugin. It's just a start and I'm not sure how the internals are working, but any suggestions welcome.

https://github.com/mccrodp/gatsby-contentful-i18n/pull/1

**Comment by gucolin** [comment]
@mccrodp Yeah it's working for us. The new i18n plugin version fixed this. We were mixing multiple starters to get everything working. By looking at #31 I assume you solved it already? If not let me know and I can dig up our source code and have a look (can't remember all the details on top of my head :P)

**Comment by mccrodp** [comment]
@gucolin, if you could get the source that'd be really awesome. I believe I'm close, but I can't get it yet. Really appreciate your feedback here and would love to see some code on how you solved the URL generation from Contentful. Thanks!

**Comment by gucolin** [comment]
We did something like this in gatsby-node.js:

`createPage({
        path: `${path}`,
        component,
        context: {
          langKey: node_locale,
          path: `${path}`
        }
      });`

Where in contentful we manually specify the 'path' with /en/ prefix or some other languages we support. For example: '/en/news/blah'. Hope that helps or let me know if you need anymore details.

**Comment by mccrodp** [comment]
I'm going to give it another go soon. As you can see over in #31, I had the idea to auto convert the path based on locale as I only have one content instance and the fields are localised rather than separate content per language in contentul.

```
createPage({
        path: `/${edge.node.node_locale}/${edge.node.slug}`,
        ...
      })
```

So, you don't get any other conflicts with this plugin? Ok, I'm going to give it another go and get back to you if I come across something more specific. Will try to create a starter repo to share on it for other beginners. Thanks for your help and letting me know it's working for you 😄

**Comment by gucolin** [comment]
Yeah that seems to be a better idea. I haven't seen any conflicts after upgrading to 0.4.1, and our website is now run 100% on contenful + gatsby + i18n. Still needs a lot of improvements but yeah it's working :)

**Comment by mccrodp** [comment]
Got this working, so many thanks for your input. Here's a repo with the start of i18n w/ default Contentful example: https://github.com/mccrodp/gatsby-contentful-i18n
