### ISSUE TITLE
Can't work with any sources except remark

### ISSUE THREAD

**Issue by Akurganow** [angeloocana/gatsby-plugin-i18n#2]
For my site i use [countentful](https://www.gatsbyjs.org/packages/gatsby-source-contentful/) as source, but your plugin by default use remark as source and i can't find how change it without fork

**Comment by angeloocana** [comment]
Hi @Akurganow  
Thank for the issue.

Did u do the fork? I wish I could see your solution.

I'm going to clean this plugin today and create gatsby-plugin-i18n-TAGS and gatsby-plugin-i18n-READNEXT , I want it to be clean as possible and work with diferentts plugins.

**Comment by angeloocana** [comment]
@Akurganow 
I just released a new simple version.
You can send the **query** throw options, maybe it helps, please let me know.

I want to make it work for everybody.

Thanks!

**Comment by angeloocana** [comment]
I'm closing this issue.

Please reopen if you still have any problem,
I really would like to help!
