### ISSUE TITLE
Force a locale other than EN?

### ISSUE THREAD

**Issue by gucolin** [angeloocana/gatsby-plugin-i18n#20]
I noticed that my Gatsby site can automatically switch locale depends on the my system locale, but I'm wondering if there's anyway to have my site "ignore" that system local and set it to whatever I required it to, other than EN?  

Note that I've set the langKeyDefault and langKeyForNull in my config to be a certain locale. # @ #

**Comment by angeloocana** [comment]
Hi @gucolin !

Are you using redirect in the /src/pages/index.js like: https://github.com/angeloocana/gatsby-starter-default-i18n/blob/master/src/pages/index.js ?

If so, you could ask to redirect directly to the default language.

Does it work?

**Comment by gucolin** [comment]
Lovely. Worked! Thanks
