### ISSUE TITLE
How to handle if the Translation page is not created

### ISSUE THREAD

**Issue by Necmttn** [angeloocana/gatsby-plugin-i18n#22]
let's say we have multiple pages which have translations for both, 
but let say one-page haven't translated 
when the user is in `example.en.js` 
switch the language to `ZH` on built version it redirects to 404. is there any way to catch this when the path is not defined. instead of navigating there fire an action etc. etc.  ?

**Comment by sedubois** [comment]
This is a duplicate of #18
