### ISSUE TITLE
Auto-detect region

### ISSUE THREAD

**Issue by vilav** [angeloocana/gatsby-plugin-i18n#3]
hello

Is there a way to combine this with server side region detection and automatically show the translated language?

**Comment by angeloocana** [comment]
Hello @vilav !

If you use a server everything is possible!
Where are you hosting?

I was thinking about just doing it in the browser.

What do you think?

**Comment by vilav** [comment]
Hi @angeloocana!

Definitely looking at Netlify with Gatsby. How do you envision doing it in the browser accurately client-side? I think that'd certainly be a more elegant solution without backend implications!

**Comment by angeloocana** [comment]
If we do the redirect just for the '/' root page, Will it work for you?

If the User goes to a page like /pt/about it should always display the 'pt' version.
If the User goes to the / root page redirects to /pt/ is Portuguese.

What do you think?

I'm concerned about google search...

**Comment by vilav** [comment]
That's perfect. I think most sites do it like that! Plus for a user it's clearer that's the locale they're on. 
How about if a user on a PT locale is an english speaking user? Could a manual selection of "EN" therefore be mad

**Comment by angeloocana** [comment]
@vilav  Done! I Hope it fits your needs =D

Working example: https://angeloocana.com

Code: https://github.com/angeloocana/angeloocana/blob/master/src/pages/index.js

Upgrade **ptz-i18n**: `yarn upgrade ptz-i18n`

Example:
```js
import { redirectToHome } from 'ptz-i18n';
class RedirectIndex extends React.PureComponent {
  constructor(args) {
    super(args);
    const { langs, defaultLangKey } = args.data.site.siteMetadata.languages;
    redirectToHome(langs, defaultLangKey);
  }

  render() {
    return (<Index {...this.props} />);
  }
}

export default RedirectIndex;
```


Please let me know what do you think about this solution!
