### ISSUE TITLE
Add all dependencies to package.json or mention them in Readme

### ISSUE THREAD

**Issue by romanenko** [angeloocana/gatsby-plugin-i18n#4]
I'm starting a new Gatsby project from scratch and adding `gatsby-plugin-i18n`. Now, the development server doesn't start, because it requires `ramda`, then `ptz-i18n`: I had to add it to my package.json to make it work.

Maybe, we should include them to our `package.json` so they are added automatically, like these guys did: https://github.com/gatsbyjs/gatsby/blob/b92402629c646655d2155fea151a8c1ec040fd64/packages/gatsby-plugin-styled-components/package.json#L8 ?

**Comment by angeloocana** [comment]
@romanenko  Sounds perfect! 

Would you like to do a Pull Request?
I can do it otherwise.

Thanks!

**Comment by romanenko** [comment]
Sorry, my bad, it does not require `ramda`. Made a PR: #5 ;)
