### ISSUE TITLE
Gatsby version

### ISSUE THREAD

**Issue by VladBlow** [angeloocana/gatsby-plugin-i18n#50]
Hey. Please, provide information about version Gatsby to Readme file, because you solution don't work with Gatsby v2

**Comment by sedubois** [comment]
@VladBlow there's a discussion here: 
https://github.com/gatsbyjs/gatsby/issues/3853

Personally I very much like [Lingui JS](https://github.com/lingui/js-lingui) which I already use, and am patiently waiting for the release of v3, after which its creator @tricoder42 said he would help provide an official Gatsby demo. He also just gave a [presentation](https://lingui.js.org/misc/talks-about-i18n.html#let-react-speak-your-language-by-tomas-ehrlich) at React Conf.

In my own test project, I don't use any Gatsby plugin, I directly integrate with DatoCMS + Lingui JS. My URLs are localized too. (My repo currently isn't open-sourced but basically it's about configuring things in gatsby-node.js)

**Comment by VladBlow** [comment]
@sedubois thank a lot. https://github.com/dcroitoru/gatsby-starter-i18n-lingui is working fine for me

**Comment by sedubois** [comment]
Yeah it might work fine to start but is for an older version as far as I remember and there’s some things it doesn’t handle. There’s also a discussion about that on the lingui repo.

**Comment by hugomn** [comment]
This plugin is working fine with Gatsby v2. I have a working example here: https://github.com/hugomn/hugomagalhaes.com

**Comment by angeloocana** [comment]
Thanks to @hugomn , @bjrn, and all the contributors this plugin is working with Gatsby v2.

@hugomn  would you like to add your website to the readme showcase?

**Comment by hugomn** [comment]
@angeloocana Thanks! =)
Feel free to add if you think it can help people using the plugin! 🙏🏻

**Comment by angeloocana** [comment]
Added!
