### ISSUE TITLE
Automatic language detection error in starter package on Gatsby v2

### ISSUE THREAD

**Issue by mccrodp** [angeloocana/gatsby-plugin-i18n#52]
Hey @angeloocana, trying to upgrade the default starter to Gatsby v2 and I'm getting an issue with the approach. As mentioned here https://github.com/angeloocana/gatsby-starter-default-i18n/issues/4 it mightn't be the best approach, but not sure if we've any other options for Gatsby V2.

````
// Skip build, Browsers only
    if (typeof window !== 'undefined') {
      const { langs, defaultLangKey } = args.data.site.siteMetadata.languages;
      const langKey = getUserLangKey(langs, defaultLangKey);
      const homeUrl = withPrefix(`/${langKey}/`);

      // I don`t think this is the best solution
      // I would like to use Gatsby Redirects like:
      // https://github.com/gatsbyjs/gatsby/tree/master/examples/using-redirects
      // But Gatsby Redirects are static, they need to be specified at build time,
      // This redirect is dynamic, It needs to know the user browser language.
      // Any ideas? Join the issue: https://github.com/angeloocana/gatsby-starter-default-i18n/issues/4
      window.___history.replace(homeUrl);
    }
````

I'm getting an error with WSOD now:

>Uncaught TypeError: Cannot read property 'replace' of undefined

Any ideas?
 

**Update:**
Added this work around for now:

````
if (typeof window.___history !== 'undefined') {
        window.___history.replace(homeUrl);
      }
      else {
        window.location.href = homeUrl;
      }
````

I jumped straight into upgrading the `gatsby-starter-contentful-i18n` starter as, so if anyone wants to use this to upgrade the starter here, here it is: https://github.com/mccrodp/gatsby-starter-contentful-i18n

Feel free to close this if it's the same status as we had before in https://github.com/angeloocana/gatsby-starter-default-i18n/issues/4 🙇

**Comment by hugomn** [comment]
Hey @mccrodp. `navigate` from gatsby will solve the issue.

```
import { graphql, navigate, withPrefix } from 'gatsby';
...
// Skip build, Browsers only
    if (typeof window !== 'undefined') {
      const { langs, defaultLangKey } = args.data.site.siteMetadata.languages;
      const langKey = getUserLangKey(langs, defaultLangKey);
      const homeUrl = withPrefix(`/${langKey}/`);

      // I don`t think this is the best solution
      // I would like to use Gatsby Redirects like: 
      // https://github.com/gatsbyjs/gatsby/tree/master/examples/using-redirects
      // But Gatsby Redirects are static, they need to be specified at build time,
      // This redirect is dynamic, It needs to know the user browser language.
      // Any ideias? Join the issue: https://github.com/hugomn/gatsby-starter-default-i18n/issues/4
      // window.___history.replace(homeUrl);
      navigate(homeUrl);
    }
  }
```

I think @angeloocana didn't have time to upgrade his starter to gatsby v2 yet. If it helps, I did it for my personal website last week: https://github.com/hugomn/hugomagalhaes.com. Cheers!

**Comment by mccrodp** [comment]
Beautiful, works a treat, thanks a lot @hugomn, and well done with the site, looking great! 😄

**Comment by angeloocana** [comment]
Thanks @hugomn !!!
