### ISSUE TITLE
How to skip lang in url for default?

### ISSUE THREAD

**Issue by hugomn** [angeloocana/gatsby-plugin-i18n#53]
Hi @angeloocana! Thanks again for the amazing plugin. I was trying to hide the /{lang}/ for the default url (only). For example to have `/blog/first-post` and `/blog/pt/first-post/` when `en` is the default language. Is there a way to do that? If not, can you quickly guide me how to implement it? 

Thanks in advance!

**Comment by hugomn** [comment]
I was just debugging a bit more and now is clear that this option is not supported yet (gatsby-plugin-i18n-tags always prefix the url with lang, so there's no workaround for now). 

I was thinking if it makes sense to include a new option in the main plugin, to avoid prefixing url's for the default lang, including all plugins, something like:

`prefixDefault: false`

Does that make sense? I can try to make a PR.

Thanks!

**Comment by angeloocana** [comment]
Hi Hugo!

We could have an array of languages and check if the URL starts with one of
them, if not we know it is the default language.

I think your idea is good about creating the option to use the default
without prefix.

Thank you for everything!

**Comment by hugomn** [comment]
@angeloocana PR created here: https://github.com/angeloocana/gatsby-plugin-i18n/pull/54

Best!

**Comment by hugomn** [comment]
Feature merged. Thanks @angeloocana! ❤️
