### ISSUE TITLE
Got error when adding 'gatsby-transformer-csv'

### ISSUE THREAD

**Issue by gucolin** [angeloocana/gatsby-plugin-i18n#9]
Run into issue when I added 'gatsby-transformer-csv'

Config: 
{
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/src/data`,
        name: 'data'
      }
    },

Error: 

TypeError: Cannot read property 'split' of undefined

  - index.js:99
    [test]/[ptz-i18n]/dist/index.js:99:27

  - _curryN.js:37
    [test]/[ramda]/src/internal/_curryN.js:37:27

  - _arity.js:6
    [test]/[ramda]/src/internal/_arity.js:6:49

  - onCreateNode.js:35 Object.onCreateNode
    [test]/[gatsby-plugin-i18n]/onCreateNode.js:35:52

  - api-runner-node.js:104 runAPI
    [test]/[gatsby]/dist/utils/api-runner-node.js:104:36

  - api-runner-node.js:178
    [test]/[gatsby]/dist/utils/api-runner-node.js:178:33

  - map.js:27
    [test]/[gatsby]/[async]/internal/map.js:27:9

  - eachOfLimit.js:64 replenish
    [test]/[gatsby]/[async]/internal/eachOfLimit.js:64:17

  - eachOfLimit.js:49 iterateeCallback
    [test]/[gatsby]/[async]/internal/eachOfLimit.js:49:17

  - onlyOnce.js:12
    [test]/[gatsby]/[async]/internal/onlyOnce.js:12:16

  - map.js:29
    [test]/[gatsby]/[async]/internal/map.js:29:13

  - util.js:16 tryCatcher
    [test]/[bluebird]/js/release/util.js:16:23

  - nodeify.js:22 Promise.successAdapter [as _fulfillmentHandler0]
    [test]/[bluebird]/js/release/nodeify.js:22:30

  - promise.js:566 Promise._settlePromise
    [test]/[bluebird]/js/release/promise.js:566:21

  - promise.js:614 Promise._settlePromise0
    [test]/[bluebird]/js/release/promise.js:614:10

  - promise.js:693 Promise._settlePromises
    [test]/[bluebird]/js/release/promise.js:693:18

  - async.js:133 Async._drainQueue
    [test]/[bluebird]/js/release/async.js:133:16

  - async.js:143 Async._drainQueues
    [test]/[bluebird]/js/release/async.js:143:10

  - async.js:17 Immediate.Async.drainQueues [as _onImmediate]
    [test]/[bluebird]/js/release/async.js:17:14

**Comment by angeloocana** [comment]
Hi @gucolin 

I added 'gatsby-transformer-csv' to [angeloocana.com](https://angeloocana.com/)
with:
`yarn add gatsby-transformer-csv`

Then I added `gatsby-transformer-csv` to `gatsby-config.js` before `gatsby-plugin-i18n`.

Then I added a csv file to `src/pages/teste.csv`
```csv
letter,value
a,65
b,66
c,67
```

And the project works fine. 
I tried moving `gatsby-transformer-csv` to the end of `gatsby-config.js` and no error. 

Can I see and test your project?
What steps are you taking?

I'd love to help.

**Comment by gucolin** [comment]
I have these plugins in my config:

plugins: [
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        path: `${__dirname}/src/pages`,
        name: 'pages'
      }
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/src/data`,
        name: 'data'
      }
    },
    {
      resolve: 'gatsby-transformer-remark',
      options: {
        plugins: [
          {
            resolve: 'gatsby-remark-images',
            options: {
              maxWidth: 750,
              linkImagesToOriginal: false,
              wrapperStyle: 'margin-bottom: 1.0725rem;'
            }
          },
          {
            resolve: 'gatsby-remark-responsive-iframe',
            options: {
              wrapperStyle: 'margin-bottom: 1.0725rem'
            }
          },
          'gatsby-remark-prismjs',
          'gatsby-remark-copy-linked-files',
          'gatsby-remark-smartypants'
        ]
      }
    },
    {
      resolve: 'gatsby-plugin-i18n',
      options: {
        langKeyForNull: 'any',
        langKeyDefault: languages.defaultLangKey,
        useLangKeyLayout: false
      }
    },
    'gatsby-transformer-csv',
    'gatsby-transformer-sharp',
    'gatsby-plugin-less',
    'gatsby-plugin-sharp',
    {
      resolve: 'gatsby-plugin-google-analytics',
      options: {
        trackingId: ``
      }
    },
    'gatsby-plugin-offline',
    'gatsby-plugin-react-helmet'

note that the second 'gatsby-source-filesystem' is loading my data folder which contains csv, as soon as I add that block I got the error, if I remove it my `gatsby develop` runs fine...

**Comment by angeloocana** [comment]
I added 
```
{
      resolve: 'gatsby-source-filesystem',
      options: {
        path: `${__dirname}/src/data`,
        name: 'data'
      }
    },
```
and the csv file to `src/data` and it is still working

What else do you have in your data folder?

Could you fork or download my project https://github.com/angeloocana/angeloocana
and add your data folder to see if it brokes?

**Comment by gucolin** [comment]
Your repo is working after adding gatsby-transformer-csv, but not sure why mine is not...from the error output do you have any idea what might be going on?

**Comment by gucolin** [comment]
Keep in mind that as soon as I remove the following block from my config file, without changing anything else, everything went back to normal
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/src/data`,
        name: 'data'
      }
    },

**Comment by angeloocana** [comment]
Fixed! 

Now it is ignoring files outside `pages` folder.

Do you think you will need to create pages from your `data` folder?
We will need to implement something to read `gatsby-source-filesystem` folders.

Thanks for opening the issue! =D

Now just update the package and let me know if it is fixed!

**Comment by gucolin** [comment]
Don't think I will need to create pages from my data folder...and yeah I can see it's working now! Very appreciate the fast turnaround and you really saved my day :)
